sudo: required
dist: trusty
language: php
php:
  - '7.0'

install:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get -y install apt-transport-https
  - sudo apt-get -y update
  - sudo apt-get -y install dotnet-sdk-2.1
  - composer config -g repo.packagist composer https://packagist.laravel-china.org
  - composer install -d ./NULASpider.PHP

script:
  - sudo bash ./Build/scripts/publish-multi-targets.sh

before_deploy:
  - curl https://github.com/lindell/github-release-cli/releases/download/1.1.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
  - export GITHUB_OAUTH_TOKEN=${GITHUB_TOKEN}
  - export releaseTitle=$(cat ./Build/Release/releaseTitle)
  - export releaseNote=$(cat ./Build/Release/releaseNote)
  - export preRelease=$(cat ./Build/Release/preRelease)
  - export BODY=${releaseNote}
  - export RELEASE_NAME=${releaseTitle}
  - export FILES=./Build/Release/*.zip

deploy:
  provider: script
  script: ./github-releaser -draft -verbose
  skip_cleanup: true
  on:
    all_branches: true
